format = """
[](#ffb4ab)\
$os\
$username\
[█](bg:#d8c770 fg:#ffb4ab)\
$directory\
[](bg:#a8d0b5 fg:#d8c770)\
$git_branch\
$git_status\
[](fg:#a8d0b5 bg:#d0c7a2)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:#d0c7a2 bg:#f5e388)\
$conda\
[](fg:#f5e388 bg:#c4ecd0)\
$time\
[ ](fg:#c4ecd0)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#ffb4ab fg:#690005"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#ffb4ab fg:#690005"
style_root = "bg:#ffb4ab fg:#690005"
format = '[ $user]($style)'

[directory]
style = "bg:#d8c770 fg:#383000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#a8d0b5"
format = '[[ $symbol $branch ](fg:#133724 bg:#a8d0b5)]($style)'

[git_status]
style = "bg:#a8d0b5"
format = '[[($all_status$ahead_behind )](fg:#133724 bg:#a8d0b5)]($style)'

[nodejs]
symbol = ""
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[c]
symbol = " "
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[rust]
symbol = ""
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[golang]
symbol = ""
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[php]
symbol = ""
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[java]
symbol = " "
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[kotlin]
symbol = ""
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[haskell]
symbol = ""
style = "bg:#d0c7a2"
format = '[[ $symbol( $version) ](fg:#363116 bg:#d0c7a2)]($style)'

[python]
symbol = ""
style = "bg:#d0c7a2"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:#363116 bg:#d0c7a2)]($style)'

[docker_context]
symbol = ""
style = "bg:#f5e388"
format = '[[ $symbol( $context) ](fg:#211c00 bg:#f5e388)]($style)'

[conda]
symbol = "  "
style = "fg:#211c00 bg:#f5e388"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:#c4ecd0"
format = '[[  $time ](fg:#002111 bg:#c4ecd0)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:#d0c7a2)'
error_symbol = '[❯](bold fg:#ffb4ab)'
vimcmd_symbol = '[❮](bold fg:#d0c7a2)'
vimcmd_replace_one_symbol = '[❮](bold fg:#c4ecd0)'
vimcmd_replace_symbol = '[❮](bold fg:#c4ecd0)'
vimcmd_visual_symbol = '[❮](bold fg:#a8d0b5)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:#c4ecd0"
disabled = false
show_notifications = true
min_time_to_notify = 45000
