format = """
[](#ffb4ab)\
$os\
$username\
[█](bg:#87d1ea fg:#ffb4ab)\
$directory\
[](bg:#c2c4eb fg:#87d1ea)\
$git_branch\
$git_status\
[](fg:#c2c4eb bg:#b3cad4)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:#b3cad4 bg:#b4ebff)\
$conda\
[](fg:#b4ebff bg:#e0e0ff)\
$time\
[ ](fg:#e0e0ff)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#ffb4ab fg:#690005"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#ffb4ab fg:#690005"
style_root = "bg:#ffb4ab fg:#690005"
format = '[ $user]($style)'

[directory]
style = "bg:#87d1ea fg:#003542"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#c2c4eb"
format = '[[ $symbol $branch ](fg:#2b2e4d bg:#c2c4eb)]($style)'

[git_status]
style = "bg:#c2c4eb"
format = '[[($all_status$ahead_behind )](fg:#2b2e4d bg:#c2c4eb)]($style)'

[nodejs]
symbol = ""
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[c]
symbol = " "
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[rust]
symbol = ""
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[golang]
symbol = ""
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[php]
symbol = ""
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[java]
symbol = " "
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[kotlin]
symbol = ""
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[haskell]
symbol = ""
style = "bg:#b3cad4"
format = '[[ $symbol( $version) ](fg:#1d333b bg:#b3cad4)]($style)'

[python]
symbol = ""
style = "bg:#b3cad4"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:#1d333b bg:#b3cad4)]($style)'

[docker_context]
symbol = ""
style = "bg:#b4ebff"
format = '[[ $symbol( $context) ](fg:#001f27 bg:#b4ebff)]($style)'

[conda]
symbol = "  "
style = "fg:#001f27 bg:#b4ebff"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:#e0e0ff"
format = '[[  $time ](fg:#161937 bg:#e0e0ff)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:#b3cad4)'
error_symbol = '[❯](bold fg:#ffb4ab)'
vimcmd_symbol = '[❮](bold fg:#b3cad4)'
vimcmd_replace_one_symbol = '[❮](bold fg:#e0e0ff)'
vimcmd_replace_symbol = '[❮](bold fg:#e0e0ff)'
vimcmd_visual_symbol = '[❮](bold fg:#c2c4eb)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:#e0e0ff"
disabled = false
show_notifications = true
min_time_to_notify = 45000
