format = """
[](#ffb4ab)\
$os\
$username\
[█](bg:#80d4d9 fg:#ffb4ab)\
$directory\
[](bg:#b5c7e9 fg:#80d4d9)\
$git_branch\
$git_status\
[](fg:#b5c7e9 bg:#b1cccd)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:#b1cccd bg:#9cf0f5)\
$conda\
[](fg:#9cf0f5 bg:#d5e3ff)\
$time\
[ ](fg:#d5e3ff)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#ffb4ab fg:#690005"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#ffb4ab fg:#690005"
style_root = "bg:#ffb4ab fg:#690005"
format = '[ $user]($style)'

[directory]
style = "bg:#80d4d9 fg:#003739"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#b5c7e9"
format = '[[ $symbol $branch ](fg:#1f314c bg:#b5c7e9)]($style)'

[git_status]
style = "bg:#b5c7e9"
format = '[[($all_status$ahead_behind )](fg:#1f314c bg:#b5c7e9)]($style)'

[nodejs]
symbol = ""
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[c]
symbol = " "
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[rust]
symbol = ""
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[golang]
symbol = ""
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[php]
symbol = ""
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[java]
symbol = " "
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[kotlin]
symbol = ""
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[haskell]
symbol = ""
style = "bg:#b1cccd"
format = '[[ $symbol( $version) ](fg:#1b3436 bg:#b1cccd)]($style)'

[python]
symbol = ""
style = "bg:#b1cccd"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:#1b3436 bg:#b1cccd)]($style)'

[docker_context]
symbol = ""
style = "bg:#9cf0f5"
format = '[[ $symbol( $context) ](fg:#002021 bg:#9cf0f5)]($style)'

[conda]
symbol = "  "
style = "fg:#002021 bg:#9cf0f5"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:#d5e3ff"
format = '[[  $time ](fg:#081c36 bg:#d5e3ff)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:#b1cccd)'
error_symbol = '[❯](bold fg:#ffb4ab)'
vimcmd_symbol = '[❮](bold fg:#b1cccd)'
vimcmd_replace_one_symbol = '[❮](bold fg:#d5e3ff)'
vimcmd_replace_symbol = '[❮](bold fg:#d5e3ff)'
vimcmd_visual_symbol = '[❮](bold fg:#b5c7e9)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:#d5e3ff"
disabled = false
show_notifications = true
min_time_to_notify = 45000
