"""
Render palette.json -> theme.js for the Spider Monkey Panel scripts.

The JS twin of render-theme-css.py, and the same substitution point: the SMP
panel scripts contain ZERO colour literals -- every colour arrives as
THEME.<role>, defined here. A future matugen template replaces this script
entirely, emitting exactly this file from the live wallpaper palette with no
other change anywhere.

WHY THE COLOURS ARE ARGB INTEGERS, NOT STRINGS
GdiGraphics takes colours as 32-bit 0xAARRGGBB integers, so the conversion has
to happen somewhere. Doing it here rather than in the panel means the panel
never parses a colour at paint time, and there is exactly one place where a
"#rrggbb" can be misread.

Writes UTF-8 with NO BOM (project house rule).
"""

import argparse
import json
import os

ROLES = [
    "surface",
    "surface_container",
    "surface_container_high",
    "on_surface",
    "on_surface_variant",
    "outline",
    "primary",
    "on_primary",
]

HEADER = """// Generated by foobar2000/render-theme-js.py from palette.json.
// Do not edit by hand -- edit palette.json and re-run.
// The panel scripts must contain no colour literals; only THEME.<role>.
//
// Values are 0xAARRGGBB integers, which is what GdiGraphics expects.
"""


def argb(hex_colour, alpha=255):
    h = hex_colour.lstrip('#')
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return (alpha << 24) | (r << 16) | (g << 8) | b


def blend(top_hex, bottom_hex, amount):
    """Composite top over bottom at `amount` (0..1), returning opaque ARGB.

    GdiGraphics has no equivalent of CSS color-mix, and a translucent fill would
    have to be composited against whatever happens to be underneath. Doing the
    blend here keeps every colour in the panels a flat, predictable value.
    """
    t = top_hex.lstrip('#')
    b = bottom_hex.lstrip('#')
    out = []
    for i in (0, 2, 4):
        tv, bv = int(t[i:i + 2], 16), int(b[i:i + 2], 16)
        out.append(int(round(tv * amount + bv * (1.0 - amount))))
    return (255 << 24) | (out[0] << 16) | (out[1] << 8) | out[2]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument('--palette', default=os.path.join(here, 'palette.json'))
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    palette = json.load(open(args.palette, 'r', encoding='utf-8'))

    missing = [r for r in ROLES if r not in palette]
    if missing:
        raise SystemExit("palette.json is missing roles: %s" % ', '.join(missing))

    lines = [HEADER, "var THEME = {"]
    for r in ROLES:
        v = palette[r]
        if not (v.startswith('#') and len(v) == 7):
            raise SystemExit("role %s has a non-#rrggbb value: %r" % (r, v))
        lines.append("    %-24s 0x%08X,   // %s" % (r + ':', argb(v), v))

    # Derived tones the design needs. Kept here rather than computed at paint
    # time so every colour in the panel still traces back to one of the eight
    # roles, and so a future matugen template only ever has to emit this file.
    lines.append("")
    lines.append("    // derived. Pre-blended to opaque values rather than left")
    lines.append("    // translucent: GdiGraphics composites against whatever is already")
    lines.append("    // on the surface, so an alpha fill would change with its backdrop.")
    lines.append("    %-24s 0x%08X,   // hairline: outline over surface_container"
                 % ('rule:', blend(palette['outline'], palette['surface_container'], 0.22)))
    lines.append("    %-24s 0x%08X,   // scroll trough"
                 % ('track:', blend(palette['outline'], palette['surface_container'], 0.20)))
    lines.append("    %-24s 0x%08X,   // tree guide spine"
                 % ('guide:', blend(palette['outline'], palette['surface_container'], 0.32)))
    lines.append("    // a raised block that is already surface_container_high needs a")
    lines.append("    // hover state ABOVE the lightest role, so lift it toward outline.")
    lines.append("    %-24s 0x%08X,   // hover on a raised block"
                 % ('raised_hover:', blend(palette['outline'], palette['surface_container_high'], 0.18)))
    lines.append("    // Finder-style row banding: barely there on purpose. Any stronger and")
    lines.append("    // it competes with the hover and selection states above it.")
    lines.append("    %-24s 0x%08X    // alternate list row"
                 % ('stripe:', blend(palette['outline'], palette['surface_container'], 0.07)))
    lines.append("};")

    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:   # utf-8, no BOM
        f.write(text)

    with open(args.out, 'rb') as f:
        head = f.read(3)
    print("wrote %s (%d bytes), BOM present: %s" % (args.out, len(text.encode('utf-8')), head == b'\xef\xbb\xbf'))
    for r in ROLES:
        print("  %-24s %s -> 0x%08X" % (r, palette[r], argb(palette[r])))


if __name__ == '__main__':
    main()
