"""
Render palette.json -> theme.css for the foo_uie_webview panel.

This is the substitution point the briefing asked about. The panel's
Template.html contains ZERO colour literals -- every colour arrives as a
var(--role) defined here -- which is the same discipline the Zebar pack uses.
A future matugen template replaces this script entirely: it would emit exactly
this file from the live wallpaper palette, with no other change anywhere.

Writes UTF-8 with NO BOM (project house rule).
"""

import argparse
import json
import os

ROLES = [
    "surface",
    "surface_container",
    "surface_container_high",
    "on_surface",
    "on_surface_variant",
    "outline",
    "primary",
    "on_primary",
]

HEADER = """/* Generated by foobar2000/render-theme-css.py from palette.json.
   Do not edit by hand -- edit palette.json and re-run.
   Template.html must contain no colour literals; only var(--role). */
"""


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument('--palette', default=os.path.join(here, 'palette.json'))
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    palette = json.load(open(args.palette, 'r', encoding='utf-8'))

    missing = [r for r in ROLES if r not in palette]
    if missing:
        raise SystemExit("palette.json is missing roles: %s" % ', '.join(missing))

    lines = [HEADER, ":root {"]
    for r in ROLES:
        v = palette[r]
        if not (v.startswith('#') and len(v) == 7):
            raise SystemExit("role %s has a non-#rrggbb value: %r" % (r, v))
        lines.append("  --%s: %s;" % (r.replace('_', '-'), v))
    lines.append("}")
    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:   # utf-8, no BOM
        f.write(text)

    with open(args.out, 'rb') as f:
        head = f.read(3)
    print("wrote %s (%d bytes), BOM present: %s" % (args.out, len(text.encode('utf-8')), head == b'\xef\xbb\xbf'))
    for r in ROLES:
        print("  --%-24s %s" % (r.replace('_', '-') + ':', palette[r]))


if __name__ == '__main__':
    main()
