# One callable entry point that brings the desktop's two restartable pieces up:
# whkd (the hotkey daemon) and every autostarted Zebar widget.
#
# WHY IT EXISTS. Nothing on this machine autostarts komorebi, whkd or zebar --
# no Startup-folder entry, no HKCU Run value, no scheduled task (checked). They
# have been started by hand every boot. On top of that, **whkd reads ~/.config/
# whkdrc exactly once, at startup**, so every whkdrc edit needs a restart before
# it means anything, and there was no single command for that either.
#
# Run it any time; it is idempotent. `-Install` also registers it to run at
# login, `-Uninstall` removes that again.
#
# WHAT IT DELIBERATELY DOES NOT DO: restart komorebi. Restarting komorebi
# retiles every real window on the desktop, so this only ever STARTS it, and
# only when -IncludeKomorebi is passed and it is not already running. A running
# komorebi is left strictly alone.

[CmdletBinding()]
param(
    # Subset switches; with neither, both parts run.
    [switch]$WhkdOnly,
    [switch]$WidgetsOnly,
    # Start komorebi too, but only if it is not already running (see above).
    [switch]$IncludeKomorebi,
    # Register / unregister this script as a login item.
    [switch]$Install,
    [switch]$Uninstall
)

if ($WhkdOnly -and $WidgetsOnly) {
    throw "-WhkdOnly and -WidgetsOnly are mutually exclusive; pass neither to run both."
}

$script:Root = Split-Path -Parent $PSScriptRoot
# The REAL binary, not the scoop shim. A shim is a launcher process in front of
# the executable, so going through it is two process creations instead of one --
# the same reasoning that moved every komorebic call in ~/.config/whkdrc off the
# shim (see CLAUDE.md, "Keybind latency").
$script:WhkdExe = Join-Path $env:USERPROFILE 'scoop\apps\whkd\current\whkd.exe'
$script:KomorebicExe = Join-Path $env:USERPROFILE 'scoop\apps\komorebi\current\komorebic.exe'
$script:StartupVbs = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup\caelestia-desktop.vbs'

function Install-LoginItem {
    <#
      A .vbs shim rather than a .cmd or a shortcut, because WScript.Shell's Run
      takes a window style and 0 genuinely means hidden -- a .cmd in the Startup
      folder flashes a console window at every login. There is already a
      clickup-scout.vbs in this same folder doing the same trick.
    #>
    $target = Join-Path $PSScriptRoot 'Start-Desktop.ps1'

    # THE LOGIN ITEM MUST CARRY -IncludeKomorebi, OR IT SOLVES NOTHING.
    #
    # Nothing on this machine autostarts komorebi -- no Startup entry, no Run
    # value, no scheduled task -- so after every reboot whkd is up, every
    # binding is valid, and every komorebi hotkey silently does nothing,
    # because `komorebic` has no komorebi to connect to. Reported as "komorebi
    # hotkeys aren't working sometimes"; the "sometimes" is simply whether the
    # stack happened to have been started by hand that session.
    #
    # The first version of this wrote a bare `-File Start-Desktop.ps1` with no
    # arguments, which meant the login item brought up whkd and the widgets and
    # STILL left komorebi down -- fixing the symptom's neighbours and not the
    # symptom. At login there is by definition no komorebi already running, so
    # the "never restart a running komorebi" rule this script is careful about
    # is not in tension with starting it here: Start-Komorebi checks and skips
    # anyway.
    $vbs = @"
' Generated by scripts/Start-Desktop.ps1 -Install. Delete this file (or run
' Start-Desktop.ps1 -Uninstall) to stop the desktop coming up at login.
CreateObject("WScript.Shell").Run "powershell -NoProfile -ExecutionPolicy Bypass -File ""$target"" -IncludeKomorebi", 0, False
"@
    # The pipeline's BOM rule: never Set-Content/Out-File a file another program parses.
    [System.IO.File]::WriteAllText($script:StartupVbs, $vbs, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "Registered at login: $script:StartupVbs"
}

function Uninstall-LoginItem {
    if (Test-Path $script:StartupVbs) {
        Remove-Item $script:StartupVbs -Force
        Write-Host "Removed login item: $script:StartupVbs"
    } else {
        Write-Host "No login item registered at $script:StartupVbs -- nothing to remove."
    }
}

function Start-Whkd {
    <#
      Restart semantics, not start-if-missing: picking up a whkdrc edit is the
      main reason to call this, and whkd only reads that file at startup.
    #>
    $existing = Get-Process whkd -ErrorAction SilentlyContinue
    if ($existing) {
        $existing | Stop-Process -Force
        Start-Sleep -Milliseconds 200
    }

    $exe = if (Test-Path $script:WhkdExe) { $script:WhkdExe } else { 'whkd' }
    if ($exe -eq 'whkd' -and -not (Get-Command whkd -ErrorAction SilentlyContinue)) {
        Write-Warning "whkd not found at $script:WhkdExe nor on PATH -- hotkeys will not work."
        return $false
    }

    Start-Process $exe -WindowStyle Hidden
    Start-Sleep -Milliseconds 400
    if (Get-Process whkd -ErrorAction SilentlyContinue) {
        $verb = if ($existing) { 'restarted' } else { 'started' }
        Write-Host "whkd $verb (was running: $([bool]$existing))."
        return $true
    }
    # whkd exits immediately on an unparseable whkdrc, which is the one failure
    # worth being loud about -- the bindings are simply gone until it is fixed.
    Write-Warning "whkd did not stay running -- check ~/.config/whkdrc for a syntax error."
    return $false
}

function Start-LauncherKey {
    <#
      The Windows-key hotkey daemon (zebar/caelestia/tools/launcher-key.exe).
      It owns a WH_KEYBOARD_LL hook and runs for the whole session -- it is
      NOT a zebar helper: zebar never spawns it (which is also what keeps it
      clear of the port-6124 inheritance trap), and Restart-ZebarWidgets
      deliberately excludes it from its reap.

      START-IF-MISSING, never restart. Re-launching it would drop and reinstall
      a global keyboard hook for no reason, and a second instance would fight
      the first for the same key.

      Found missing live: the Windows key had fallen back to the default Start
      menu because nothing was starting this at all -- Install-Config's
      Set-LauncherKeyAutostart had never been run on this machine, so there was
      no Startup shortcut and no running daemon.
    #>
    if (Get-Process launcher-key -ErrorAction SilentlyContinue) {
        Write-Host "launcher-key already running -- left alone (it owns a keyboard hook)."
        return
    }
    $exe = Join-Path $script:Root 'zebar\caelestia\tools\launcher-key.exe'
    if (-not (Test-Path $exe)) {
        Write-Warning "launcher-key.exe not found at $exe -- the Windows key will not open the launcher. Build it with csc.exe (see the header of tools/launcher-key.cs)."
        return
    }
    Start-Process $exe -WindowStyle Hidden
    Write-Host "launcher-key started (Windows key opens the launcher)."
}

function Start-Komorebi {
    if (Get-Process komorebi -ErrorAction SilentlyContinue) {
        Write-Host "komorebi already running -- left alone (a restart would retile every window)."
        return
    }
    if (-not (Test-Path $script:KomorebicExe)) {
        Write-Warning "komorebic not found at $script:KomorebicExe -- skipping."
        return
    }
    # No --whkd: this script owns whkd's lifecycle, and letting komorebi spawn a
    # second one would leave two daemons racing for the same hotkeys.
    #
    # VERIFIED, NOT FIRED AND FORGOTTEN. `komorebic start` is genuinely flaky:
    # run by hand it printed "komorebi.exe did not start... Trying again" and
    # only succeeded on its second attempt. Launched detached and hidden, that
    # first failure is completely invisible -- this used to print "komorebi
    # started." and return regardless, so a silent failure looked identical to
    # success. Reported as "komorebi isn't starting", with whkd up and the bar
    # up, which is exactly what a fire-and-forget start produces.
    #
    # So: start it, then WAIT for the process to actually exist, and retry once
    # if it does not. Waiting on the process rather than on `komorebic state`
    # deliberately -- the IPC socket comes up after the process does, so
    # polling state would report failure during a slow but healthy start.
    for ($attempt = 1; $attempt -le 2; $attempt++) {
        Start-Process $script:KomorebicExe -ArgumentList 'start' -WindowStyle Hidden

        $deadline = (Get-Date).AddSeconds(20)
        while ((Get-Date) -lt $deadline) {
            if (Get-Process komorebi -ErrorAction SilentlyContinue) {
                Write-Host "komorebi started."
                return
            }
            Start-Sleep -Milliseconds 300
        }

        if ($attempt -eq 1) {
            Write-Warning "komorebi did not come up within 20s -- retrying once."
        }
    }

    Write-Warning "komorebi FAILED TO START after two attempts. Run '$script:KomorebicExe start' in a visible console to see why -- launched hidden, its own error output goes nowhere."
}

if ($Uninstall) { Uninstall-LoginItem; return }
if ($Install)   { Install-LoginItem }

if ($IncludeKomorebi -and -not $WidgetsOnly) { Start-Komorebi }

if (-not $WidgetsOnly) {
    Start-Whkd | Out-Null
    # Grouped with whkd rather than with the widgets: both are hotkey daemons
    # that live outside zebar and outlive a widget restart.
    Start-LauncherKey
}

if (-not $WhkdOnly) {
    # Restart-ZebarWidgets is worth reusing rather than reimplementing: it
    # restarts EVERY entry in ~/.glzr/zebar/settings.json's startupConfigs (a
    # naive restart silently drops the other autostarted pack), starts each one
    # detached because start-widget-preset blocks its caller for as long as the
    # widget lives, and reaps the orphaned helper processes first -- one of
    # which, left behind, inherits zebar's listening socket on port 6124 and
    # makes every later start paint nothing at all.
    #
    # Dot-sourcing Apply-Theme.ps1 only DEFINES its functions; it themes nothing.
    . "$PSScriptRoot\Apply-Theme.ps1"
    Restart-ZebarWidgets
}
