// Generated by foobar2000/render-theme-js.py from palette.json.
// Do not edit by hand -- edit palette.json and re-run.
// The panel scripts must contain no colour literals; only THEME.<role>.
//
// Values are 0xAARRGGBB integers, which is what GdiGraphics expects.

var THEME = {
    surface:                 0xFF0E1415,   // #0e1415
    surface_container:       0xFF1A2121,   // #1a2121
    surface_container_high:  0xFF252B2B,   // #252b2b
    on_surface:              0xFFDDE4E4,   // #dde4e4
    on_surface_variant:      0xFFBEC8C9,   // #bec8c9
    outline:                 0xFF899393,   // #899393
    primary:                 0xFF80D4D9,   // #80d4d9
    on_primary:              0xFF003739,   // #003739

    // derived. Pre-blended to opaque values rather than left
    // translucent: GdiGraphics composites against whatever is already
    // on the surface, so an alpha fill would change with its backdrop.
    rule:                    0xFF323A3A,   // hairline: outline over surface_container
    track:                   0xFF303838,   // scroll trough
    guide:                   0xFF3E4545,   // tree guide spine
    // a raised block that is already surface_container_high needs a
    // hover state ABOVE the lightest role, so lift it toward outline.
    raised_hover:            0xFF373E3E,   // hover on a raised block
    // Finder-style row banding: barely there on purpose. Any stronger and
    // it competes with the hover and selection states above it.
    stripe:                  0xFF222929    // alternate list row
};
