-- Generated by matugen. Do not edit.
--
-- Design notes (matugen 4.1.0; every role name below is checked against the
-- 50 `colors.*` roles in docs/matugen-reference.md -- no substitutions were
-- needed, all 13 distinct roles used here exist verbatim):
--
-- `primary`/`secondary`/`tertiary`/`error` (tone ~80 in dark mode) and their
-- `on_X_container` siblings (tone ~90) are the two tiers actually used below.
-- This was verified, not assumed, by rendering this exact role set through
-- matugen against 4 wallpapers with visibly different dominant hues (olive/
-- teal/blue/maroon probe images, `--prefer saturation`) and computing sRGB
-- relative luminance + WCAG contrast against `surface`:
--   primary / secondary / tertiary / error           ~10.9:1 vs surface (ansi)
--   on_primary_container / on_secondary_container /
--   on_tertiary_container / on_error_container        ~14.4:1 vs surface (brights)
-- Both tiers were stable across all 4 wallpapers (tone-driven, not
-- hue-driven -- consistent with the Task 5 finding for tacky-borders).
-- Every `brights[i]` measured strictly brighter than its `ansi[i]` sibling.
--
-- Deliberately AVOIDED here, per the Task 4/5 lessons -- and re-confirmed by
-- the same measurement pass:
--   `primary_container` (and its secondary/tertiary/error siblings) alone --
--     these are DARK tones in dark mode (measured ~2.0:1 vs surface), not
--     readable as terminal foreground text.
--   `inverse_primary` -- measured ~2.87:1 vs surface; it's built to contrast
--     against `inverse_surface` (light-toned in dark mode), not `surface`,
--     so it reads as a mid-dark tone here, not a bright one.
--
-- matugen only synthesizes 4 distinct accent hues from one wallpaper
-- (primary/secondary/tertiary/error) -- one short of ANSI's 6 chromatic
-- slots (red/green/yellow/blue/magenta/cyan). `magenta` reuses the `error`
-- hue and `cyan` reuses the `tertiary` hue rather than inventing two hues
-- that don't exist in the source palette -- the same accommodation
-- ~/.wezterm.lua's own "Monokai Pro Octagon" scheme already makes for its
-- cyan slot ("no true cyan in its palette, so the cyan slot carries the
-- orange accent").
return {
  surface    = "{{colors.surface.default.hex}}",
  on_surface = "{{colors.on_surface.default.hex}}",
  primary    = "{{colors.primary.default.hex}}",

  ansi = {
    "{{colors.surface_container_highest.default.hex}}", -- black
    "{{colors.error.default.hex}}",                      -- red
    "{{colors.tertiary.default.hex}}",                    -- green
    "{{colors.secondary.default.hex}}",                   -- yellow
    "{{colors.primary.default.hex}}",                     -- blue
    "{{colors.error.default.hex}}",                       -- magenta (reuses red's hue -- see note above)
    "{{colors.tertiary.default.hex}}",                     -- cyan (reuses green's hue -- see note above)
    "{{colors.on_surface_variant.default.hex}}",          -- white
  },
  brights = {
    "{{colors.outline.default.hex}}",                     -- bright black
    "{{colors.on_error_container.default.hex}}",          -- bright red
    "{{colors.on_tertiary_container.default.hex}}",       -- bright green
    "{{colors.on_secondary_container.default.hex}}",      -- bright yellow
    "{{colors.on_primary_container.default.hex}}",        -- bright blue
    "{{colors.on_error_container.default.hex}}",          -- bright magenta
    "{{colors.on_tertiary_container.default.hex}}",        -- bright cyan
    "{{colors.on_surface.default.hex}}",                  -- bright white
  },
}
