format = """
[]({{colors.error.default.hex}})\
$os\
$username\
[█](bg:{{colors.primary.default.hex}} fg:{{colors.error.default.hex}})\
$directory\
[](bg:{{colors.tertiary.default.hex}} fg:{{colors.primary.default.hex}})\
$git_branch\
$git_status\
[](fg:{{colors.tertiary.default.hex}} bg:{{colors.secondary.default.hex}})\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:{{colors.secondary.default.hex}} bg:{{colors.primary_fixed.default.hex}})\
$conda\
[](fg:{{colors.primary_fixed.default.hex}} bg:{{colors.tertiary_fixed.default.hex}})\
$time\
[ ](fg:{{colors.tertiary_fixed.default.hex}})\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:{{colors.error.default.hex}} fg:{{colors.on_error.default.hex}}"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:{{colors.error.default.hex}} fg:{{colors.on_error.default.hex}}"
style_root = "bg:{{colors.error.default.hex}} fg:{{colors.on_error.default.hex}}"
format = '[ $user]($style)'

[directory]
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:{{colors.tertiary.default.hex}}"
format = '[[ $symbol $branch ](fg:{{colors.on_tertiary.default.hex}} bg:{{colors.tertiary.default.hex}})]($style)'

[git_status]
style = "bg:{{colors.tertiary.default.hex}}"
format = '[[($all_status$ahead_behind )](fg:{{colors.on_tertiary.default.hex}} bg:{{colors.tertiary.default.hex}})]($style)'

[nodejs]
symbol = ""
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[c]
symbol = " "
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[rust]
symbol = ""
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[golang]
symbol = ""
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[php]
symbol = ""
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[java]
symbol = " "
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[kotlin]
symbol = ""
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[haskell]
symbol = ""
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[python]
symbol = ""
style = "bg:{{colors.secondary.default.hex}}"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:{{colors.on_secondary.default.hex}} bg:{{colors.secondary.default.hex}})]($style)'

[docker_context]
symbol = ""
style = "bg:{{colors.primary_fixed.default.hex}}"
format = '[[ $symbol( $context) ](fg:{{colors.on_primary_fixed.default.hex}} bg:{{colors.primary_fixed.default.hex}})]($style)'

[conda]
symbol = "  "
style = "fg:{{colors.on_primary_fixed.default.hex}} bg:{{colors.primary_fixed.default.hex}}"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:{{colors.tertiary_fixed.default.hex}}"
format = '[[  $time ](fg:{{colors.on_tertiary_fixed.default.hex}} bg:{{colors.tertiary_fixed.default.hex}})]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:{{colors.secondary.default.hex}})'
error_symbol = '[❯](bold fg:{{colors.error.default.hex}})'
vimcmd_symbol = '[❮](bold fg:{{colors.secondary.default.hex}})'
vimcmd_replace_one_symbol = '[❮](bold fg:{{colors.tertiary_fixed.default.hex}})'
vimcmd_replace_symbol = '[❮](bold fg:{{colors.tertiary_fixed.default.hex}})'
vimcmd_visual_symbol = '[❮](bold fg:{{colors.tertiary.default.hex}})'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:{{colors.tertiary_fixed.default.hex}}"
disabled = false
show_notifications = true
min_time_to_notify = 45000
